<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${loginPage.title}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0, user-scalable=no">
</head>
<body>
    <div>
        <span>登录成功，欢迎光临</span>
        <a href="${path.basePath}${path.logoutUrl}">退出</a>
    </div>
</body>
</html>